### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by edunham** [samfoo/servo-starters#2]
I'm looking at detaching https://github.com/servo/servo-starters from this repo so it looks like the origin and this looks like the fork, since you've marked this repo as deprecated. Although it looks like you intended this repo to be open source code for others to modify and use, it would be better to supply a license file to reduce any ambiguity about how others can use the tool. 

A README would also be nice, but isn't really essential. 

Thank you for building this tool!

**Comment by samfoo** [comment]
Done.
